AjaxExampleApp/Controllers/AjaxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AjaxExampleApp.Models;

namespace AjaxExampleApp.Controllers
{
    public class AjaxController : Controller
    {
        //
        // GET: /Ajax/
        public ActionResult Index()
        {
            return View();
        }

        private List<Product> GetAllProducts()
        {
            return new List<Product>()
            {
                new Product(){Code = "P-001",Name = "Product-001",UnitPrice = 101},
                new Product(){Code = "P-002",Name = "Product-002",UnitPrice = 102},
                new Product(){Code = "P-003",Name = "Product-003",UnitPrice = 103},
                new Product(){Code = "P-004",Name = "Product-004",UnitPrice = 104},
                new Product(){Code = "P-005",Name = "Product-005",UnitPrice = 105},
                new Product(){Code = "P-006",Name = "Product-006",UnitPrice = 106},
                new Product(){Code = "P-007",Name = "Product-007",UnitPrice = 107},
                new Product(){Code = "P-008",Name = "Product-008",UnitPrice = 108},
                new Product(){Code = "P-009",Name = "Product-009",UnitPrice = 109},
            };
        } 
        public PartialViewResult ShowDetails()
        {
            System.Threading.Thread.Sleep(3000);
            string code = Request.Form["txtCode"];
            List<Product> productList = GetAllProducts();
            Product prod = productList.FirstOrDefault(c => c.Code == code);
            return PartialView("_ShowDetails", prod);
        }
	}
}

AjaxExampleApp/Views/Ajax/Index.cshtml
@using AjaxExampleApp.Models

@{
    ViewBag.Title = "Index";
}


@using (Ajax.BeginForm("ShowDetails", "Ajax",
    new AjaxOptions
    {
        HttpMethod = "POST",
        UpdateTargetId = "div1",
        InsertionMode = InsertionMode.Replace,
        LoadingElementId = "waitimage"
    }))
{
    <h2></h2>
        <table>
            <tr>
                
                <td>Product Code</td>
                <td>@Html.TextBox("txtCode",null,new{@class="form-control"})</td>
            </tr>
            <tr>
                <td></td>
                <td><input type="submit" class="btn btn-success" value="Show Details"/>
                    <input type="reset" class="btn btn-danger" value="Clear" /><img id="waitimage" src="~/Images/InternetSlowdown_Day.gif" height="50" width="50" style="display: none" /></td>
                
            </tr>
        </table>
        
        
        
        
   

}


<br />

<br />
<div id="div1">
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>

AjaxExampleApp/Views/Ajax/_ShowDetails.cshtml
@model AjaxExampleApp.Models.Product

@if (Model==null || Model.Code==null)
{
    <h1>Please provide valid product code</h1>
}

else
{
    <h3>Product Details</h3>
    <table class="table table-border table-striped">
        <tr>
            <th>Product Code</th>
            <th>Product Name</th>
            <th>Product Price</th>

        </tr>
        <tr>
            <td>@Model.Code</td>
            <td>@Model.Name</td>
            <td>@Model.UnitPrice</td>
            
        </tr>
    </table>
}